// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BATCHNORMBACKWARDATTRIBUTES_HIPDNN_SDK_H_
#define FLATBUFFERS_GENERATED_BATCHNORMBACKWARDATTRIBUTES_HIPDNN_SDK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn {
namespace sdk {

struct BatchNormBackwardAttributes;
struct BatchNormBackwardAttributesBuilder;
struct BatchNormBackwardAttributesT;

bool operator==(const BatchNormBackwardAttributesT &lhs, const BatchNormBackwardAttributesT &rhs);
bool operator!=(const BatchNormBackwardAttributesT &lhs, const BatchNormBackwardAttributesT &rhs);

struct BatchNormBackwardAttributesT : public ::flatbuffers::NativeTable {
  typedef BatchNormBackwardAttributes TableType;
  int64_t dy = 0;
  int64_t x = 0;
  ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt;
  int64_t scale = 0;
  std::vector<int64_t> peer_stats{};
  int64_t dx = 0;
  int64_t dscale = 0;
  int64_t dbias = 0;
};

struct BatchNormBackwardAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchNormBackwardAttributesT NativeTableType;
  typedef BatchNormBackwardAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DY = 4,
    VT_X = 6,
    VT_MEAN = 8,
    VT_INV_VARIANCE = 10,
    VT_SCALE = 12,
    VT_PEER_STATS = 14,
    VT_DX = 16,
    VT_DSCALE = 18,
    VT_DBIAS = 20
  };
  int64_t dy() const {
    return GetField<int64_t>(VT_DY, 0);
  }
  bool mutate_dy(int64_t _dy = 0) {
    return SetField<int64_t>(VT_DY, _dy, 0);
  }
  int64_t x() const {
    return GetField<int64_t>(VT_X, 0);
  }
  bool mutate_x(int64_t _x = 0) {
    return SetField<int64_t>(VT_X, _x, 0);
  }
  ::flatbuffers::Optional<int64_t> mean() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN);
  }
  bool mutate_mean(int64_t _mean) {
    return SetField<int64_t>(VT_MEAN, _mean);
  }
  ::flatbuffers::Optional<int64_t> inv_variance() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE);
  }
  bool mutate_inv_variance(int64_t _inv_variance) {
    return SetField<int64_t>(VT_INV_VARIANCE, _inv_variance);
  }
  int64_t scale() const {
    return GetField<int64_t>(VT_SCALE, 0);
  }
  bool mutate_scale(int64_t _scale = 0) {
    return SetField<int64_t>(VT_SCALE, _scale, 0);
  }
  const ::flatbuffers::Vector<int64_t> *peer_stats() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_PEER_STATS);
  }
  ::flatbuffers::Vector<int64_t> *mutable_peer_stats() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_PEER_STATS);
  }
  int64_t dx() const {
    return GetField<int64_t>(VT_DX, 0);
  }
  bool mutate_dx(int64_t _dx = 0) {
    return SetField<int64_t>(VT_DX, _dx, 0);
  }
  int64_t dscale() const {
    return GetField<int64_t>(VT_DSCALE, 0);
  }
  bool mutate_dscale(int64_t _dscale = 0) {
    return SetField<int64_t>(VT_DSCALE, _dscale, 0);
  }
  int64_t dbias() const {
    return GetField<int64_t>(VT_DBIAS, 0);
  }
  bool mutate_dbias(int64_t _dbias = 0) {
    return SetField<int64_t>(VT_DBIAS, _dbias, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_DY, 8) &&
           VerifyField<int64_t>(verifier, VT_X, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE, 8) &&
           VerifyOffset(verifier, VT_PEER_STATS) &&
           verifier.VerifyVector(peer_stats()) &&
           VerifyField<int64_t>(verifier, VT_DX, 8) &&
           VerifyField<int64_t>(verifier, VT_DSCALE, 8) &&
           VerifyField<int64_t>(verifier, VT_DBIAS, 8) &&
           verifier.EndTable();
  }
  BatchNormBackwardAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchNormBackwardAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BatchNormBackwardAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormBackwardAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchNormBackwardAttributesBuilder {
  typedef BatchNormBackwardAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dy(int64_t dy) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_DY, dy, 0);
  }
  void add_x(int64_t x) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_X, x, 0);
  }
  void add_mean(int64_t mean) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_MEAN, mean);
  }
  void add_inv_variance(int64_t inv_variance) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_INV_VARIANCE, inv_variance);
  }
  void add_scale(int64_t scale) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_SCALE, scale, 0);
  }
  void add_peer_stats(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> peer_stats) {
    fbb_.AddOffset(BatchNormBackwardAttributes::VT_PEER_STATS, peer_stats);
  }
  void add_dx(int64_t dx) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_DX, dx, 0);
  }
  void add_dscale(int64_t dscale) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_DSCALE, dscale, 0);
  }
  void add_dbias(int64_t dbias) {
    fbb_.AddElement<int64_t>(BatchNormBackwardAttributes::VT_DBIAS, dbias, 0);
  }
  explicit BatchNormBackwardAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchNormBackwardAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchNormBackwardAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchNormBackwardAttributes> CreateBatchNormBackwardAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t dy = 0,
    int64_t x = 0,
    ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt,
    int64_t scale = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> peer_stats = 0,
    int64_t dx = 0,
    int64_t dscale = 0,
    int64_t dbias = 0) {
  BatchNormBackwardAttributesBuilder builder_(_fbb);
  builder_.add_dbias(dbias);
  builder_.add_dscale(dscale);
  builder_.add_dx(dx);
  builder_.add_scale(scale);
  if(inv_variance) { builder_.add_inv_variance(*inv_variance); }
  if(mean) { builder_.add_mean(*mean); }
  builder_.add_x(x);
  builder_.add_dy(dy);
  builder_.add_peer_stats(peer_stats);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BatchNormBackwardAttributes> CreateBatchNormBackwardAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t dy = 0,
    int64_t x = 0,
    ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt,
    int64_t scale = 0,
    const std::vector<int64_t> *peer_stats = nullptr,
    int64_t dx = 0,
    int64_t dscale = 0,
    int64_t dbias = 0) {
  auto peer_stats__ = peer_stats ? _fbb.CreateVector<int64_t>(*peer_stats) : 0;
  return hipdnn::sdk::CreateBatchNormBackwardAttributes(
      _fbb,
      dy,
      x,
      mean,
      inv_variance,
      scale,
      peer_stats__,
      dx,
      dscale,
      dbias);
}

::flatbuffers::Offset<BatchNormBackwardAttributes> CreateBatchNormBackwardAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormBackwardAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const BatchNormBackwardAttributesT &lhs, const BatchNormBackwardAttributesT &rhs) {
  return
      (lhs.dy == rhs.dy) &&
      (lhs.x == rhs.x) &&
      (lhs.mean == rhs.mean) &&
      (lhs.inv_variance == rhs.inv_variance) &&
      (lhs.scale == rhs.scale) &&
      (lhs.peer_stats == rhs.peer_stats) &&
      (lhs.dx == rhs.dx) &&
      (lhs.dscale == rhs.dscale) &&
      (lhs.dbias == rhs.dbias);
}

inline bool operator!=(const BatchNormBackwardAttributesT &lhs, const BatchNormBackwardAttributesT &rhs) {
    return !(lhs == rhs);
}


inline BatchNormBackwardAttributesT *BatchNormBackwardAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchNormBackwardAttributesT>(new BatchNormBackwardAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BatchNormBackwardAttributes::UnPackTo(BatchNormBackwardAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dy(); _o->dy = _e; }
  { auto _e = x(); _o->x = _e; }
  { auto _e = mean(); _o->mean = _e; }
  { auto _e = inv_variance(); _o->inv_variance = _e; }
  { auto _e = scale(); _o->scale = _e; }
  { auto _e = peer_stats(); if (_e) { _o->peer_stats.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->peer_stats[_i] = _e->Get(_i); } } else { _o->peer_stats.resize(0); } }
  { auto _e = dx(); _o->dx = _e; }
  { auto _e = dscale(); _o->dscale = _e; }
  { auto _e = dbias(); _o->dbias = _e; }
}

inline ::flatbuffers::Offset<BatchNormBackwardAttributes> BatchNormBackwardAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormBackwardAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatchNormBackwardAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BatchNormBackwardAttributes> CreateBatchNormBackwardAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormBackwardAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchNormBackwardAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dy = _o->dy;
  auto _x = _o->x;
  auto _mean = _o->mean;
  auto _inv_variance = _o->inv_variance;
  auto _scale = _o->scale;
  auto _peer_stats = _o->peer_stats.size() ? _fbb.CreateVector(_o->peer_stats) : 0;
  auto _dx = _o->dx;
  auto _dscale = _o->dscale;
  auto _dbias = _o->dbias;
  return hipdnn::sdk::CreateBatchNormBackwardAttributes(
      _fbb,
      _dy,
      _x,
      _mean,
      _inv_variance,
      _scale,
      _peer_stats,
      _dx,
      _dscale,
      _dbias);
}

}  // namespace sdk
}  // namespace hipdnn

#endif  // FLATBUFFERS_GENERATED_BATCHNORMBACKWARDATTRIBUTES_HIPDNN_SDK_H_
