// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_H_
#define FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn {
namespace sdk {

struct BatchNormInferenceAttributes;
struct BatchNormInferenceAttributesBuilder;
struct BatchNormInferenceAttributesT;

bool operator==(const BatchNormInferenceAttributesT &lhs, const BatchNormInferenceAttributesT &rhs);
bool operator!=(const BatchNormInferenceAttributesT &lhs, const BatchNormInferenceAttributesT &rhs);

struct BatchNormInferenceAttributesT : public ::flatbuffers::NativeTable {
  typedef BatchNormInferenceAttributes TableType;
  int64_t x = 0;
  ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt;
  int64_t scale = 0;
  int64_t bias = 0;
  int64_t y = 0;
};

struct BatchNormInferenceAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchNormInferenceAttributesT NativeTableType;
  typedef BatchNormInferenceAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_MEAN = 6,
    VT_INV_VARIANCE = 8,
    VT_SCALE = 10,
    VT_BIAS = 12,
    VT_Y = 14
  };
  int64_t x() const {
    return GetField<int64_t>(VT_X, 0);
  }
  bool mutate_x(int64_t _x = 0) {
    return SetField<int64_t>(VT_X, _x, 0);
  }
  ::flatbuffers::Optional<int64_t> mean() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN);
  }
  bool mutate_mean(int64_t _mean) {
    return SetField<int64_t>(VT_MEAN, _mean);
  }
  ::flatbuffers::Optional<int64_t> inv_variance() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE);
  }
  bool mutate_inv_variance(int64_t _inv_variance) {
    return SetField<int64_t>(VT_INV_VARIANCE, _inv_variance);
  }
  int64_t scale() const {
    return GetField<int64_t>(VT_SCALE, 0);
  }
  bool mutate_scale(int64_t _scale = 0) {
    return SetField<int64_t>(VT_SCALE, _scale, 0);
  }
  int64_t bias() const {
    return GetField<int64_t>(VT_BIAS, 0);
  }
  bool mutate_bias(int64_t _bias = 0) {
    return SetField<int64_t>(VT_BIAS, _bias, 0);
  }
  int64_t y() const {
    return GetField<int64_t>(VT_Y, 0);
  }
  bool mutate_y(int64_t _y = 0) {
    return SetField<int64_t>(VT_Y, _y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE, 8) &&
           VerifyField<int64_t>(verifier, VT_BIAS, 8) &&
           VerifyField<int64_t>(verifier, VT_Y, 8) &&
           verifier.EndTable();
  }
  BatchNormInferenceAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchNormInferenceAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BatchNormInferenceAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormInferenceAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchNormInferenceAttributesBuilder {
  typedef BatchNormInferenceAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int64_t x) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_X, x, 0);
  }
  void add_mean(int64_t mean) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_MEAN, mean);
  }
  void add_inv_variance(int64_t inv_variance) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_INV_VARIANCE, inv_variance);
  }
  void add_scale(int64_t scale) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_SCALE, scale, 0);
  }
  void add_bias(int64_t bias) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_BIAS, bias, 0);
  }
  void add_y(int64_t y) {
    fbb_.AddElement<int64_t>(BatchNormInferenceAttributes::VT_Y, y, 0);
  }
  explicit BatchNormInferenceAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchNormInferenceAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchNormInferenceAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchNormInferenceAttributes> CreateBatchNormInferenceAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x = 0,
    ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt,
    int64_t scale = 0,
    int64_t bias = 0,
    int64_t y = 0) {
  BatchNormInferenceAttributesBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_bias(bias);
  builder_.add_scale(scale);
  if(inv_variance) { builder_.add_inv_variance(*inv_variance); }
  if(mean) { builder_.add_mean(*mean); }
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<BatchNormInferenceAttributes> CreateBatchNormInferenceAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormInferenceAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const BatchNormInferenceAttributesT &lhs, const BatchNormInferenceAttributesT &rhs) {
  return
      (lhs.x == rhs.x) &&
      (lhs.mean == rhs.mean) &&
      (lhs.inv_variance == rhs.inv_variance) &&
      (lhs.scale == rhs.scale) &&
      (lhs.bias == rhs.bias) &&
      (lhs.y == rhs.y);
}

inline bool operator!=(const BatchNormInferenceAttributesT &lhs, const BatchNormInferenceAttributesT &rhs) {
    return !(lhs == rhs);
}


inline BatchNormInferenceAttributesT *BatchNormInferenceAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchNormInferenceAttributesT>(new BatchNormInferenceAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BatchNormInferenceAttributes::UnPackTo(BatchNormInferenceAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = mean(); _o->mean = _e; }
  { auto _e = inv_variance(); _o->inv_variance = _e; }
  { auto _e = scale(); _o->scale = _e; }
  { auto _e = bias(); _o->bias = _e; }
  { auto _e = y(); _o->y = _e; }
}

inline ::flatbuffers::Offset<BatchNormInferenceAttributes> BatchNormInferenceAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormInferenceAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatchNormInferenceAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BatchNormInferenceAttributes> CreateBatchNormInferenceAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchNormInferenceAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchNormInferenceAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _mean = _o->mean;
  auto _inv_variance = _o->inv_variance;
  auto _scale = _o->scale;
  auto _bias = _o->bias;
  auto _y = _o->y;
  return hipdnn::sdk::CreateBatchNormInferenceAttributes(
      _fbb,
      _x,
      _mean,
      _inv_variance,
      _scale,
      _bias,
      _y);
}

}  // namespace sdk
}  // namespace hipdnn

#endif  // FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_H_
