// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_H_
#define FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");


namespace hipdnn {
namespace sdk {

enum DataType : int8_t {
  DataType_UNSET = 0,
  DataType_FLOAT = 1,
  DataType_HALF = 2,
  DataType_BFLOAT16 = 3,
  DataType_MIN = DataType_UNSET,
  DataType_MAX = DataType_BFLOAT16
};

inline const DataType (&EnumValuesDataType())[4] {
  static const DataType values[] = {
    DataType_UNSET,
    DataType_FLOAT,
    DataType_HALF,
    DataType_BFLOAT16
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[5] = {
    "UNSET",
    "FLOAT",
    "HALF",
    "BFLOAT16",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (::flatbuffers::IsOutRange(e, DataType_UNSET, DataType_BFLOAT16)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

}  // namespace sdk
}  // namespace hipdnn

#endif  // FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_H_
