// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

include "tensor_attributes.fbs";

namespace hipdnn_sdk.data_objects;

table BatchnormAttributes {
    x: TensorID;
    scale: TensorID;
    bias: TensorID;
    epsilon: TensorID;
    peer_stats: [TensorID];
    prev_running_mean: TensorID;
    prev_running_variance: TensorID;
    momentum: TensorID;
    y: TensorID;
    mean: TensorID;
    inv_variance: TensorID;
    next_running_mean: TensorID;
    next_running_variance: TensorID;
}