// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

include "tensor_attributes.fbs";

namespace hipdnn_sdk.data_objects;

table BatchnormAttributes {
    x: TensorID (native_inline);
    scale: TensorID (native_inline);
    bias: TensorID (native_inline);
    epsilon: TensorID (native_inline);
    peer_stats: [TensorID];
    prev_running_mean: TensorID;
    prev_running_variance: TensorID;
    momentum: TensorID ;
    y: TensorID (native_inline);
    mean: TensorID;
    inv_variance: TensorID;
    next_running_mean: TensorID;
    next_running_variance: TensorID;
}