// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

namespace hipdnn_sdk.data_objects;

table BatchnormAttributes {
    x_tid: long;
    scale_tid: long;
    bias_tid: long;
    epsilon_tid: long;
    peer_stats_tid: [long];
    prev_running_mean_tid: long = null;
    prev_running_variance_tid: long = null;
    momentum_tid: long = null;
    y_tid: long;
    mean_tid: long = null;
    inv_variance_tid: long = null;
    next_running_mean_tid: long = null;
    next_running_variance_tid: long = null;
}