FROM ubuntu:24.04 AS hipdnn

# ARG to build for specific GPU support (default to gfx90a)
ARG AMDGPU_FAMILIES=gfx90a

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Set hip platform to avoid platform detection errors
ENV HIP_PLATFORM=amd

# Install system dependencies for TheRock and other developer tools.
RUN apt-get update && apt-get install -y \
    gfortran \
    git-lfs \
    ninja-build \
    cmake \
    g++ \
    pkg-config \
    xxd \
    patchelf \
    automake \
    python3-venv \
    python3-dev \
    libegl1-mesa-dev \
    curl \
    unzip \
    patchelf \
    libtool \
    python3-pip \
    vim \
    rsync \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ROCm/TheRock.git
WORKDIR /TheRock

RUN python3 -m venv /opt/venv

#enable venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install -r requirements.txt
RUN python ./build_tools/fetch_sources.py

RUN mkdir build
WORKDIR /TheRock/build

RUN cmake -GNinja .. -DTHEROCK_ENABLE_ALL=OFF -DTHEROCK_ENABLE_MIOPEN=ON -DTHEROCK_AMDGPU_FAMILIES=$AMDGPU_FAMILIES -DCMAKE_INSTALL_PREFIX=/opt/rocm

RUN cmake --build .

RUN cmake --install .

ENV PATH="/opt/rocm/bin:/opt/rocm:${PATH}"
ENV CMAKE_GENERATOR="Ninja"
