// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct BatchnormInferenceAttributes;
struct BatchnormInferenceAttributesBuilder;
struct BatchnormInferenceAttributesT;

bool operator==(const BatchnormInferenceAttributesT &lhs, const BatchnormInferenceAttributesT &rhs);
bool operator!=(const BatchnormInferenceAttributesT &lhs, const BatchnormInferenceAttributesT &rhs);

struct BatchnormInferenceAttributesT : public ::flatbuffers::NativeTable {
  typedef BatchnormInferenceAttributes TableType;
  int64_t x = 0;
  ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt;
  int64_t scale = 0;
  int64_t bias = 0;
  int64_t y = 0;
};

struct BatchnormInferenceAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchnormInferenceAttributesT NativeTableType;
  typedef BatchnormInferenceAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_MEAN = 6,
    VT_INV_VARIANCE = 8,
    VT_SCALE = 10,
    VT_BIAS = 12,
    VT_Y = 14
  };
  int64_t x() const {
    return GetField<int64_t>(VT_X, 0);
  }
  bool mutate_x(int64_t _x = 0) {
    return SetField<int64_t>(VT_X, _x, 0);
  }
  ::flatbuffers::Optional<int64_t> mean() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN);
  }
  bool mutate_mean(int64_t _mean) {
    return SetField<int64_t>(VT_MEAN, _mean);
  }
  ::flatbuffers::Optional<int64_t> inv_variance() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE);
  }
  bool mutate_inv_variance(int64_t _inv_variance) {
    return SetField<int64_t>(VT_INV_VARIANCE, _inv_variance);
  }
  int64_t scale() const {
    return GetField<int64_t>(VT_SCALE, 0);
  }
  bool mutate_scale(int64_t _scale = 0) {
    return SetField<int64_t>(VT_SCALE, _scale, 0);
  }
  int64_t bias() const {
    return GetField<int64_t>(VT_BIAS, 0);
  }
  bool mutate_bias(int64_t _bias = 0) {
    return SetField<int64_t>(VT_BIAS, _bias, 0);
  }
  int64_t y() const {
    return GetField<int64_t>(VT_Y, 0);
  }
  bool mutate_y(int64_t _y = 0) {
    return SetField<int64_t>(VT_Y, _y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE, 8) &&
           VerifyField<int64_t>(verifier, VT_BIAS, 8) &&
           VerifyField<int64_t>(verifier, VT_Y, 8) &&
           verifier.EndTable();
  }
  BatchnormInferenceAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchnormInferenceAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BatchnormInferenceAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchnormInferenceAttributesBuilder {
  typedef BatchnormInferenceAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int64_t x) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_X, x, 0);
  }
  void add_mean(int64_t mean) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_MEAN, mean);
  }
  void add_inv_variance(int64_t inv_variance) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_INV_VARIANCE, inv_variance);
  }
  void add_scale(int64_t scale) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_SCALE, scale, 0);
  }
  void add_bias(int64_t bias) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_BIAS, bias, 0);
  }
  void add_y(int64_t y) {
    fbb_.AddElement<int64_t>(BatchnormInferenceAttributes::VT_Y, y, 0);
  }
  explicit BatchnormInferenceAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchnormInferenceAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchnormInferenceAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchnormInferenceAttributes> CreateBatchnormInferenceAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x = 0,
    ::flatbuffers::Optional<int64_t> mean = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance = ::flatbuffers::nullopt,
    int64_t scale = 0,
    int64_t bias = 0,
    int64_t y = 0) {
  BatchnormInferenceAttributesBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_bias(bias);
  builder_.add_scale(scale);
  if(inv_variance) { builder_.add_inv_variance(*inv_variance); }
  if(mean) { builder_.add_mean(*mean); }
  builder_.add_x(x);
  return builder_.Finish();
}

::flatbuffers::Offset<BatchnormInferenceAttributes> CreateBatchnormInferenceAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const BatchnormInferenceAttributesT &lhs, const BatchnormInferenceAttributesT &rhs) {
  return
      (lhs.x == rhs.x) &&
      (lhs.mean == rhs.mean) &&
      (lhs.inv_variance == rhs.inv_variance) &&
      (lhs.scale == rhs.scale) &&
      (lhs.bias == rhs.bias) &&
      (lhs.y == rhs.y);
}

inline bool operator!=(const BatchnormInferenceAttributesT &lhs, const BatchnormInferenceAttributesT &rhs) {
    return !(lhs == rhs);
}


inline BatchnormInferenceAttributesT *BatchnormInferenceAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchnormInferenceAttributesT>(new BatchnormInferenceAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BatchnormInferenceAttributes::UnPackTo(BatchnormInferenceAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x(); _o->x = _e; }
  { auto _e = mean(); _o->mean = _e; }
  { auto _e = inv_variance(); _o->inv_variance = _e; }
  { auto _e = scale(); _o->scale = _e; }
  { auto _e = bias(); _o->bias = _e; }
  { auto _e = y(); _o->y = _e; }
}

inline ::flatbuffers::Offset<BatchnormInferenceAttributes> BatchnormInferenceAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatchnormInferenceAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BatchnormInferenceAttributes> CreateBatchnormInferenceAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormInferenceAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchnormInferenceAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x = _o->x;
  auto _mean = _o->mean;
  auto _inv_variance = _o->inv_variance;
  auto _scale = _o->scale;
  auto _bias = _o->bias;
  auto _y = _o->y;
  return hipdnn_sdk::data_objects::CreateBatchnormInferenceAttributes(
      _fbb,
      _x,
      _mean,
      _inv_variance,
      _scale,
      _bias,
      _y);
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_BATCHNORMINFERENCEATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
