// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BATCHNORMATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_BATCHNORMATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct BatchnormAttributes;
struct BatchnormAttributesBuilder;
struct BatchnormAttributesT;

bool operator==(const BatchnormAttributesT &lhs, const BatchnormAttributesT &rhs);
bool operator!=(const BatchnormAttributesT &lhs, const BatchnormAttributesT &rhs);

struct BatchnormAttributesT : public ::flatbuffers::NativeTable {
  typedef BatchnormAttributes TableType;
  int64_t x_tid = 0;
  int64_t scale_tid = 0;
  int64_t bias_tid = 0;
  int64_t epsilon_tid = 0;
  std::vector<int64_t> peer_stats_tid{};
  ::flatbuffers::Optional<int64_t> prev_running_mean_tid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> prev_running_variance_tid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> momentum_tid = ::flatbuffers::nullopt;
  int64_t y_tid = 0;
  ::flatbuffers::Optional<int64_t> mean_tid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> inv_variance_tid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> next_running_mean_tid = ::flatbuffers::nullopt;
  ::flatbuffers::Optional<int64_t> next_running_variance_tid = ::flatbuffers::nullopt;
};

struct BatchnormAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchnormAttributesT NativeTableType;
  typedef BatchnormAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TID = 4,
    VT_SCALE_TID = 6,
    VT_BIAS_TID = 8,
    VT_EPSILON_TID = 10,
    VT_PEER_STATS_TID = 12,
    VT_PREV_RUNNING_MEAN_TID = 14,
    VT_PREV_RUNNING_VARIANCE_TID = 16,
    VT_MOMENTUM_TID = 18,
    VT_Y_TID = 20,
    VT_MEAN_TID = 22,
    VT_INV_VARIANCE_TID = 24,
    VT_NEXT_RUNNING_MEAN_TID = 26,
    VT_NEXT_RUNNING_VARIANCE_TID = 28
  };
  int64_t x_tid() const {
    return GetField<int64_t>(VT_X_TID, 0);
  }
  bool mutate_x_tid(int64_t _x_tid = 0) {
    return SetField<int64_t>(VT_X_TID, _x_tid, 0);
  }
  int64_t scale_tid() const {
    return GetField<int64_t>(VT_SCALE_TID, 0);
  }
  bool mutate_scale_tid(int64_t _scale_tid = 0) {
    return SetField<int64_t>(VT_SCALE_TID, _scale_tid, 0);
  }
  int64_t bias_tid() const {
    return GetField<int64_t>(VT_BIAS_TID, 0);
  }
  bool mutate_bias_tid(int64_t _bias_tid = 0) {
    return SetField<int64_t>(VT_BIAS_TID, _bias_tid, 0);
  }
  int64_t epsilon_tid() const {
    return GetField<int64_t>(VT_EPSILON_TID, 0);
  }
  bool mutate_epsilon_tid(int64_t _epsilon_tid = 0) {
    return SetField<int64_t>(VT_EPSILON_TID, _epsilon_tid, 0);
  }
  const ::flatbuffers::Vector<int64_t> *peer_stats_tid() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_PEER_STATS_TID);
  }
  ::flatbuffers::Vector<int64_t> *mutable_peer_stats_tid() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_PEER_STATS_TID);
  }
  ::flatbuffers::Optional<int64_t> prev_running_mean_tid() const {
    return GetOptional<int64_t, int64_t>(VT_PREV_RUNNING_MEAN_TID);
  }
  bool mutate_prev_running_mean_tid(int64_t _prev_running_mean_tid) {
    return SetField<int64_t>(VT_PREV_RUNNING_MEAN_TID, _prev_running_mean_tid);
  }
  ::flatbuffers::Optional<int64_t> prev_running_variance_tid() const {
    return GetOptional<int64_t, int64_t>(VT_PREV_RUNNING_VARIANCE_TID);
  }
  bool mutate_prev_running_variance_tid(int64_t _prev_running_variance_tid) {
    return SetField<int64_t>(VT_PREV_RUNNING_VARIANCE_TID, _prev_running_variance_tid);
  }
  ::flatbuffers::Optional<int64_t> momentum_tid() const {
    return GetOptional<int64_t, int64_t>(VT_MOMENTUM_TID);
  }
  bool mutate_momentum_tid(int64_t _momentum_tid) {
    return SetField<int64_t>(VT_MOMENTUM_TID, _momentum_tid);
  }
  int64_t y_tid() const {
    return GetField<int64_t>(VT_Y_TID, 0);
  }
  bool mutate_y_tid(int64_t _y_tid = 0) {
    return SetField<int64_t>(VT_Y_TID, _y_tid, 0);
  }
  ::flatbuffers::Optional<int64_t> mean_tid() const {
    return GetOptional<int64_t, int64_t>(VT_MEAN_TID);
  }
  bool mutate_mean_tid(int64_t _mean_tid) {
    return SetField<int64_t>(VT_MEAN_TID, _mean_tid);
  }
  ::flatbuffers::Optional<int64_t> inv_variance_tid() const {
    return GetOptional<int64_t, int64_t>(VT_INV_VARIANCE_TID);
  }
  bool mutate_inv_variance_tid(int64_t _inv_variance_tid) {
    return SetField<int64_t>(VT_INV_VARIANCE_TID, _inv_variance_tid);
  }
  ::flatbuffers::Optional<int64_t> next_running_mean_tid() const {
    return GetOptional<int64_t, int64_t>(VT_NEXT_RUNNING_MEAN_TID);
  }
  bool mutate_next_running_mean_tid(int64_t _next_running_mean_tid) {
    return SetField<int64_t>(VT_NEXT_RUNNING_MEAN_TID, _next_running_mean_tid);
  }
  ::flatbuffers::Optional<int64_t> next_running_variance_tid() const {
    return GetOptional<int64_t, int64_t>(VT_NEXT_RUNNING_VARIANCE_TID);
  }
  bool mutate_next_running_variance_tid(int64_t _next_running_variance_tid) {
    return SetField<int64_t>(VT_NEXT_RUNNING_VARIANCE_TID, _next_running_variance_tid);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_BIAS_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_EPSILON_TID, 8) &&
           VerifyOffset(verifier, VT_PEER_STATS_TID) &&
           verifier.VerifyVector(peer_stats_tid()) &&
           VerifyField<int64_t>(verifier, VT_PREV_RUNNING_MEAN_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_PREV_RUNNING_VARIANCE_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_MOMENTUM_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_MEAN_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_VARIANCE_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_NEXT_RUNNING_MEAN_TID, 8) &&
           VerifyField<int64_t>(verifier, VT_NEXT_RUNNING_VARIANCE_TID, 8) &&
           verifier.EndTable();
  }
  BatchnormAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BatchnormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<BatchnormAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BatchnormAttributesBuilder {
  typedef BatchnormAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tid(int64_t x_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_X_TID, x_tid, 0);
  }
  void add_scale_tid(int64_t scale_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_SCALE_TID, scale_tid, 0);
  }
  void add_bias_tid(int64_t bias_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_BIAS_TID, bias_tid, 0);
  }
  void add_epsilon_tid(int64_t epsilon_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_EPSILON_TID, epsilon_tid, 0);
  }
  void add_peer_stats_tid(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> peer_stats_tid) {
    fbb_.AddOffset(BatchnormAttributes::VT_PEER_STATS_TID, peer_stats_tid);
  }
  void add_prev_running_mean_tid(int64_t prev_running_mean_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_PREV_RUNNING_MEAN_TID, prev_running_mean_tid);
  }
  void add_prev_running_variance_tid(int64_t prev_running_variance_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_PREV_RUNNING_VARIANCE_TID, prev_running_variance_tid);
  }
  void add_momentum_tid(int64_t momentum_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_MOMENTUM_TID, momentum_tid);
  }
  void add_y_tid(int64_t y_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_Y_TID, y_tid, 0);
  }
  void add_mean_tid(int64_t mean_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_MEAN_TID, mean_tid);
  }
  void add_inv_variance_tid(int64_t inv_variance_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_INV_VARIANCE_TID, inv_variance_tid);
  }
  void add_next_running_mean_tid(int64_t next_running_mean_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_NEXT_RUNNING_MEAN_TID, next_running_mean_tid);
  }
  void add_next_running_variance_tid(int64_t next_running_variance_tid) {
    fbb_.AddElement<int64_t>(BatchnormAttributes::VT_NEXT_RUNNING_VARIANCE_TID, next_running_variance_tid);
  }
  explicit BatchnormAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchnormAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchnormAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchnormAttributes> CreateBatchnormAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tid = 0,
    int64_t scale_tid = 0,
    int64_t bias_tid = 0,
    int64_t epsilon_tid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> peer_stats_tid = 0,
    ::flatbuffers::Optional<int64_t> prev_running_mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> prev_running_variance_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> momentum_tid = ::flatbuffers::nullopt,
    int64_t y_tid = 0,
    ::flatbuffers::Optional<int64_t> mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> next_running_mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> next_running_variance_tid = ::flatbuffers::nullopt) {
  BatchnormAttributesBuilder builder_(_fbb);
  if(next_running_variance_tid) { builder_.add_next_running_variance_tid(*next_running_variance_tid); }
  if(next_running_mean_tid) { builder_.add_next_running_mean_tid(*next_running_mean_tid); }
  if(inv_variance_tid) { builder_.add_inv_variance_tid(*inv_variance_tid); }
  if(mean_tid) { builder_.add_mean_tid(*mean_tid); }
  builder_.add_y_tid(y_tid);
  if(momentum_tid) { builder_.add_momentum_tid(*momentum_tid); }
  if(prev_running_variance_tid) { builder_.add_prev_running_variance_tid(*prev_running_variance_tid); }
  if(prev_running_mean_tid) { builder_.add_prev_running_mean_tid(*prev_running_mean_tid); }
  builder_.add_epsilon_tid(epsilon_tid);
  builder_.add_bias_tid(bias_tid);
  builder_.add_scale_tid(scale_tid);
  builder_.add_x_tid(x_tid);
  builder_.add_peer_stats_tid(peer_stats_tid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BatchnormAttributes> CreateBatchnormAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tid = 0,
    int64_t scale_tid = 0,
    int64_t bias_tid = 0,
    int64_t epsilon_tid = 0,
    const std::vector<int64_t> *peer_stats_tid = nullptr,
    ::flatbuffers::Optional<int64_t> prev_running_mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> prev_running_variance_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> momentum_tid = ::flatbuffers::nullopt,
    int64_t y_tid = 0,
    ::flatbuffers::Optional<int64_t> mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> inv_variance_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> next_running_mean_tid = ::flatbuffers::nullopt,
    ::flatbuffers::Optional<int64_t> next_running_variance_tid = ::flatbuffers::nullopt) {
  auto peer_stats_tid__ = peer_stats_tid ? _fbb.CreateVector<int64_t>(*peer_stats_tid) : 0;
  return hipdnn_sdk::data_objects::CreateBatchnormAttributes(
      _fbb,
      x_tid,
      scale_tid,
      bias_tid,
      epsilon_tid,
      peer_stats_tid__,
      prev_running_mean_tid,
      prev_running_variance_tid,
      momentum_tid,
      y_tid,
      mean_tid,
      inv_variance_tid,
      next_running_mean_tid,
      next_running_variance_tid);
}

::flatbuffers::Offset<BatchnormAttributes> CreateBatchnormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const BatchnormAttributesT &lhs, const BatchnormAttributesT &rhs) {
  return
      (lhs.x_tid == rhs.x_tid) &&
      (lhs.scale_tid == rhs.scale_tid) &&
      (lhs.bias_tid == rhs.bias_tid) &&
      (lhs.epsilon_tid == rhs.epsilon_tid) &&
      (lhs.peer_stats_tid == rhs.peer_stats_tid) &&
      (lhs.prev_running_mean_tid == rhs.prev_running_mean_tid) &&
      (lhs.prev_running_variance_tid == rhs.prev_running_variance_tid) &&
      (lhs.momentum_tid == rhs.momentum_tid) &&
      (lhs.y_tid == rhs.y_tid) &&
      (lhs.mean_tid == rhs.mean_tid) &&
      (lhs.inv_variance_tid == rhs.inv_variance_tid) &&
      (lhs.next_running_mean_tid == rhs.next_running_mean_tid) &&
      (lhs.next_running_variance_tid == rhs.next_running_variance_tid);
}

inline bool operator!=(const BatchnormAttributesT &lhs, const BatchnormAttributesT &rhs) {
    return !(lhs == rhs);
}


inline BatchnormAttributesT *BatchnormAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BatchnormAttributesT>(new BatchnormAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void BatchnormAttributes::UnPackTo(BatchnormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tid(); _o->x_tid = _e; }
  { auto _e = scale_tid(); _o->scale_tid = _e; }
  { auto _e = bias_tid(); _o->bias_tid = _e; }
  { auto _e = epsilon_tid(); _o->epsilon_tid = _e; }
  { auto _e = peer_stats_tid(); if (_e) { _o->peer_stats_tid.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->peer_stats_tid[_i] = _e->Get(_i); } } else { _o->peer_stats_tid.resize(0); } }
  { auto _e = prev_running_mean_tid(); _o->prev_running_mean_tid = _e; }
  { auto _e = prev_running_variance_tid(); _o->prev_running_variance_tid = _e; }
  { auto _e = momentum_tid(); _o->momentum_tid = _e; }
  { auto _e = y_tid(); _o->y_tid = _e; }
  { auto _e = mean_tid(); _o->mean_tid = _e; }
  { auto _e = inv_variance_tid(); _o->inv_variance_tid = _e; }
  { auto _e = next_running_mean_tid(); _o->next_running_mean_tid = _e; }
  { auto _e = next_running_variance_tid(); _o->next_running_variance_tid = _e; }
}

inline ::flatbuffers::Offset<BatchnormAttributes> BatchnormAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBatchnormAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<BatchnormAttributes> CreateBatchnormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const BatchnormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BatchnormAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tid = _o->x_tid;
  auto _scale_tid = _o->scale_tid;
  auto _bias_tid = _o->bias_tid;
  auto _epsilon_tid = _o->epsilon_tid;
  auto _peer_stats_tid = _o->peer_stats_tid.size() ? _fbb.CreateVector(_o->peer_stats_tid) : 0;
  auto _prev_running_mean_tid = _o->prev_running_mean_tid;
  auto _prev_running_variance_tid = _o->prev_running_variance_tid;
  auto _momentum_tid = _o->momentum_tid;
  auto _y_tid = _o->y_tid;
  auto _mean_tid = _o->mean_tid;
  auto _inv_variance_tid = _o->inv_variance_tid;
  auto _next_running_mean_tid = _o->next_running_mean_tid;
  auto _next_running_variance_tid = _o->next_running_variance_tid;
  return hipdnn_sdk::data_objects::CreateBatchnormAttributes(
      _fbb,
      _x_tid,
      _scale_tid,
      _bias_tid,
      _epsilon_tid,
      _peer_stats_tid,
      _prev_running_mean_tid,
      _prev_running_variance_tid,
      _momentum_tid,
      _y_tid,
      _mean_tid,
      _inv_variance_tid,
      _next_running_mean_tid,
      _next_running_variance_tid);
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_BATCHNORMATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
