// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");


namespace hipdnn_sdk {
namespace data_objects {

enum DataType : int8_t {
  DataType_UNSET = 0,
  DataType_FLOAT = 1,
  DataType_HALF = 2,
  DataType_BFLOAT16 = 3,
  DataType_DOUBLE = 4,
  DataType_UINT8 = 5,
  DataType_INT32 = 6,
  DataType_MIN = DataType_UNSET,
  DataType_MAX = DataType_INT32
};

inline const DataType (&EnumValuesDataType())[7] {
  static const DataType values[] = {
    DataType_UNSET,
    DataType_FLOAT,
    DataType_HALF,
    DataType_BFLOAT16,
    DataType_DOUBLE,
    DataType_UINT8,
    DataType_INT32
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[8] = {
    "UNSET",
    "FLOAT",
    "HALF",
    "BFLOAT16",
    "DOUBLE",
    "UINT8",
    "INT32",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (::flatbuffers::IsOutRange(e, DataType_UNSET, DataType_INT32)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_DATATYPES_HIPDNN_SDK_DATA_OBJECTS_H_
