// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DEVICEBUFFERS_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_DEVICEBUFFERS_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct DeviceBuffer;
struct DeviceBufferBuilder;
struct DeviceBufferT;

struct DeviceBuffers;
struct DeviceBuffersBuilder;
struct DeviceBuffersT;

bool operator==(const DeviceBufferT &lhs, const DeviceBufferT &rhs);
bool operator!=(const DeviceBufferT &lhs, const DeviceBufferT &rhs);
bool operator==(const DeviceBuffersT &lhs, const DeviceBuffersT &rhs);
bool operator!=(const DeviceBuffersT &lhs, const DeviceBuffersT &rhs);

struct DeviceBufferT : public ::flatbuffers::NativeTable {
  typedef DeviceBuffer TableType;
  int64_t uid = 0;
  uint64_t ptr = 0;
};

struct DeviceBuffer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceBufferT NativeTableType;
  typedef DeviceBufferBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_PTR = 6
  };
  int64_t uid() const {
    return GetField<int64_t>(VT_UID, 0);
  }
  bool mutate_uid(int64_t _uid = 0) {
    return SetField<int64_t>(VT_UID, _uid, 0);
  }
  uint64_t ptr() const {
    return GetField<uint64_t>(VT_PTR, 0);
  }
  bool mutate_ptr(uint64_t _ptr = 0) {
    return SetField<uint64_t>(VT_PTR, _ptr, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_UID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PTR, 8) &&
           verifier.EndTable();
  }
  DeviceBufferT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DeviceBufferT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DeviceBuffer> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DeviceBufferBuilder {
  typedef DeviceBuffer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(int64_t uid) {
    fbb_.AddElement<int64_t>(DeviceBuffer::VT_UID, uid, 0);
  }
  void add_ptr(uint64_t ptr) {
    fbb_.AddElement<uint64_t>(DeviceBuffer::VT_PTR, ptr, 0);
  }
  explicit DeviceBufferBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceBuffer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceBuffer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceBuffer> CreateDeviceBuffer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    uint64_t ptr = 0) {
  DeviceBufferBuilder builder_(_fbb);
  builder_.add_ptr(ptr);
  builder_.add_uid(uid);
  return builder_.Finish();
}

::flatbuffers::Offset<DeviceBuffer> CreateDeviceBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DeviceBuffersT : public ::flatbuffers::NativeTable {
  typedef DeviceBuffers TableType;
  std::vector<std::unique_ptr<hipdnn_sdk::data_objects::DeviceBufferT>> io_buffers{};
  uint64_t workspace_ptr = 0;
  DeviceBuffersT() = default;
  DeviceBuffersT(const DeviceBuffersT &o);
  DeviceBuffersT(DeviceBuffersT&&) FLATBUFFERS_NOEXCEPT = default;
  DeviceBuffersT &operator=(DeviceBuffersT o) FLATBUFFERS_NOEXCEPT;
};

struct DeviceBuffers FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DeviceBuffersT NativeTableType;
  typedef DeviceBuffersBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IO_BUFFERS = 4,
    VT_WORKSPACE_PTR = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> *io_buffers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> *>(VT_IO_BUFFERS);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> *mutable_io_buffers() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> *>(VT_IO_BUFFERS);
  }
  uint64_t workspace_ptr() const {
    return GetField<uint64_t>(VT_WORKSPACE_PTR, 0);
  }
  bool mutate_workspace_ptr(uint64_t _workspace_ptr = 0) {
    return SetField<uint64_t>(VT_WORKSPACE_PTR, _workspace_ptr, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_IO_BUFFERS) &&
           verifier.VerifyVector(io_buffers()) &&
           verifier.VerifyVectorOfTables(io_buffers()) &&
           VerifyField<uint64_t>(verifier, VT_WORKSPACE_PTR, 8) &&
           verifier.EndTable();
  }
  DeviceBuffersT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DeviceBuffersT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DeviceBuffers> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBuffersT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DeviceBuffersBuilder {
  typedef DeviceBuffers Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_io_buffers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>>> io_buffers) {
    fbb_.AddOffset(DeviceBuffers::VT_IO_BUFFERS, io_buffers);
  }
  void add_workspace_ptr(uint64_t workspace_ptr) {
    fbb_.AddElement<uint64_t>(DeviceBuffers::VT_WORKSPACE_PTR, workspace_ptr, 0);
  }
  explicit DeviceBuffersBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DeviceBuffers> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DeviceBuffers>(end);
    fbb_.Required(o, DeviceBuffers::VT_IO_BUFFERS);
    return o;
  }
};

inline ::flatbuffers::Offset<DeviceBuffers> CreateDeviceBuffers(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>>> io_buffers = 0,
    uint64_t workspace_ptr = 0) {
  DeviceBuffersBuilder builder_(_fbb);
  builder_.add_workspace_ptr(workspace_ptr);
  builder_.add_io_buffers(io_buffers);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DeviceBuffers> CreateDeviceBuffersDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> *io_buffers = nullptr,
    uint64_t workspace_ptr = 0) {
  auto io_buffers__ = io_buffers ? _fbb.CreateVector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>>(*io_buffers) : 0;
  return hipdnn_sdk::data_objects::CreateDeviceBuffers(
      _fbb,
      io_buffers__,
      workspace_ptr);
}

::flatbuffers::Offset<DeviceBuffers> CreateDeviceBuffers(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBuffersT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const DeviceBufferT &lhs, const DeviceBufferT &rhs) {
  return
      (lhs.uid == rhs.uid) &&
      (lhs.ptr == rhs.ptr);
}

inline bool operator!=(const DeviceBufferT &lhs, const DeviceBufferT &rhs) {
    return !(lhs == rhs);
}


inline DeviceBufferT *DeviceBuffer::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DeviceBufferT>(new DeviceBufferT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DeviceBuffer::UnPackTo(DeviceBufferT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = uid(); _o->uid = _e; }
  { auto _e = ptr(); _o->ptr = _e; }
}

inline ::flatbuffers::Offset<DeviceBuffer> DeviceBuffer::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBufferT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDeviceBuffer(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DeviceBuffer> CreateDeviceBuffer(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBufferT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DeviceBufferT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _uid = _o->uid;
  auto _ptr = _o->ptr;
  return hipdnn_sdk::data_objects::CreateDeviceBuffer(
      _fbb,
      _uid,
      _ptr);
}


inline bool operator==(const DeviceBuffersT &lhs, const DeviceBuffersT &rhs) {
  return
      (lhs.io_buffers.size() == rhs.io_buffers.size() && std::equal(lhs.io_buffers.cbegin(), lhs.io_buffers.cend(), rhs.io_buffers.cbegin(), [](std::unique_ptr<hipdnn_sdk::data_objects::DeviceBufferT> const &a, std::unique_ptr<hipdnn_sdk::data_objects::DeviceBufferT> const &b) { return (a == b) || (a && b && *a == *b); })) &&
      (lhs.workspace_ptr == rhs.workspace_ptr);
}

inline bool operator!=(const DeviceBuffersT &lhs, const DeviceBuffersT &rhs) {
    return !(lhs == rhs);
}


inline DeviceBuffersT::DeviceBuffersT(const DeviceBuffersT &o)
      : workspace_ptr(o.workspace_ptr) {
  io_buffers.reserve(o.io_buffers.size());
  for (const auto &io_buffers_ : o.io_buffers) { io_buffers.emplace_back((io_buffers_) ? new hipdnn_sdk::data_objects::DeviceBufferT(*io_buffers_) : nullptr); }
}

inline DeviceBuffersT &DeviceBuffersT::operator=(DeviceBuffersT o) FLATBUFFERS_NOEXCEPT {
  std::swap(io_buffers, o.io_buffers);
  std::swap(workspace_ptr, o.workspace_ptr);
  return *this;
}

inline DeviceBuffersT *DeviceBuffers::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<DeviceBuffersT>(new DeviceBuffersT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DeviceBuffers::UnPackTo(DeviceBuffersT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = io_buffers(); if (_e) { _o->io_buffers.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->io_buffers[_i]) { _e->Get(_i)->UnPackTo(_o->io_buffers[_i].get(), _resolver); } else { _o->io_buffers[_i] = std::unique_ptr<hipdnn_sdk::data_objects::DeviceBufferT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->io_buffers.resize(0); } }
  { auto _e = workspace_ptr(); _o->workspace_ptr = _e; }
}

inline ::flatbuffers::Offset<DeviceBuffers> DeviceBuffers::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBuffersT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDeviceBuffers(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DeviceBuffers> CreateDeviceBuffers(::flatbuffers::FlatBufferBuilder &_fbb, const DeviceBuffersT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DeviceBuffersT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _io_buffers = _fbb.CreateVector<::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffer>> (_o->io_buffers.size(), [](size_t i, _VectorArgs *__va) { return CreateDeviceBuffer(*__va->__fbb, __va->__o->io_buffers[i].get(), __va->__rehasher); }, &_va );
  auto _workspace_ptr = _o->workspace_ptr;
  return hipdnn_sdk::data_objects::CreateDeviceBuffers(
      _fbb,
      _io_buffers,
      _workspace_ptr);
}

inline const hipdnn_sdk::data_objects::DeviceBuffers *GetDeviceBuffers(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_sdk::data_objects::DeviceBuffers>(buf);
}

inline const hipdnn_sdk::data_objects::DeviceBuffers *GetSizePrefixedDeviceBuffers(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_sdk::data_objects::DeviceBuffers>(buf);
}

inline DeviceBuffers *GetMutableDeviceBuffers(void *buf) {
  return ::flatbuffers::GetMutableRoot<DeviceBuffers>(buf);
}

inline hipdnn_sdk::data_objects::DeviceBuffers *GetMutableSizePrefixedDeviceBuffers(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_sdk::data_objects::DeviceBuffers>(buf);
}

inline bool VerifyDeviceBuffersBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_sdk::data_objects::DeviceBuffers>(nullptr);
}

inline bool VerifySizePrefixedDeviceBuffersBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_sdk::data_objects::DeviceBuffers>(nullptr);
}

inline void FinishDeviceBuffersBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffers> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDeviceBuffersBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::DeviceBuffers> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hipdnn_sdk::data_objects::DeviceBuffersT> UnPackDeviceBuffers(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::DeviceBuffersT>(GetDeviceBuffers(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_sdk::data_objects::DeviceBuffersT> UnPackSizePrefixedDeviceBuffers(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::DeviceBuffersT>(GetSizePrefixedDeviceBuffers(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_DEVICEBUFFERS_HIPDNN_SDK_DATA_OBJECTS_H_
