// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINE_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_ENGINE_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct Engine;
struct EngineBuilder;
struct EngineT;

struct EngineContainer;
struct EngineContainerBuilder;
struct EngineContainerT;

bool operator==(const EngineT &lhs, const EngineT &rhs);
bool operator!=(const EngineT &lhs, const EngineT &rhs);
bool operator==(const EngineContainerT &lhs, const EngineContainerT &rhs);
bool operator!=(const EngineContainerT &lhs, const EngineContainerT &rhs);

struct EngineT : public ::flatbuffers::NativeTable {
  typedef Engine TableType;
  int64_t engine_id = 0;
};

struct Engine FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineT NativeTableType;
  typedef EngineBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENGINE_ID = 4
  };
  int64_t engine_id() const {
    return GetField<int64_t>(VT_ENGINE_ID, 0);
  }
  bool mutate_engine_id(int64_t _engine_id = 0) {
    return SetField<int64_t>(VT_ENGINE_ID, _engine_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ENGINE_ID, 8) &&
           verifier.EndTable();
  }
  EngineT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EngineT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Engine> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EngineBuilder {
  typedef Engine Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_engine_id(int64_t engine_id) {
    fbb_.AddElement<int64_t>(Engine::VT_ENGINE_ID, engine_id, 0);
  }
  explicit EngineBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Engine> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Engine>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Engine> CreateEngine(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t engine_id = 0) {
  EngineBuilder builder_(_fbb);
  builder_.add_engine_id(engine_id);
  return builder_.Finish();
}

::flatbuffers::Offset<Engine> CreateEngine(::flatbuffers::FlatBufferBuilder &_fbb, const EngineT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct EngineContainerT : public ::flatbuffers::NativeTable {
  typedef EngineContainer TableType;
  std::vector<std::unique_ptr<hipdnn_sdk::data_objects::EngineT>> engines{};
  EngineContainerT() = default;
  EngineContainerT(const EngineContainerT &o);
  EngineContainerT(EngineContainerT&&) FLATBUFFERS_NOEXCEPT = default;
  EngineContainerT &operator=(EngineContainerT o) FLATBUFFERS_NOEXCEPT;
};

struct EngineContainer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineContainerT NativeTableType;
  typedef EngineContainerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENGINES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> *engines() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> *>(VT_ENGINES);
  }
  ::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> *mutable_engines() {
    return GetPointer<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> *>(VT_ENGINES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENGINES) &&
           verifier.VerifyVector(engines()) &&
           verifier.VerifyVectorOfTables(engines()) &&
           verifier.EndTable();
  }
  EngineContainerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EngineContainerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EngineContainer> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineContainerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EngineContainerBuilder {
  typedef EngineContainer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_engines(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>>> engines) {
    fbb_.AddOffset(EngineContainer::VT_ENGINES, engines);
  }
  explicit EngineContainerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineContainer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineContainer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineContainer> CreateEngineContainer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>>> engines = 0) {
  EngineContainerBuilder builder_(_fbb);
  builder_.add_engines(engines);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EngineContainer> CreateEngineContainerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> *engines = nullptr) {
  auto engines__ = engines ? _fbb.CreateVector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>>(*engines) : 0;
  return hipdnn_sdk::data_objects::CreateEngineContainer(
      _fbb,
      engines__);
}

::flatbuffers::Offset<EngineContainer> CreateEngineContainer(::flatbuffers::FlatBufferBuilder &_fbb, const EngineContainerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const EngineT &lhs, const EngineT &rhs) {
  return
      (lhs.engine_id == rhs.engine_id);
}

inline bool operator!=(const EngineT &lhs, const EngineT &rhs) {
    return !(lhs == rhs);
}


inline EngineT *Engine::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EngineT>(new EngineT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Engine::UnPackTo(EngineT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = engine_id(); _o->engine_id = _e; }
}

inline ::flatbuffers::Offset<Engine> Engine::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEngine(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Engine> CreateEngine(::flatbuffers::FlatBufferBuilder &_fbb, const EngineT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EngineT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _engine_id = _o->engine_id;
  return hipdnn_sdk::data_objects::CreateEngine(
      _fbb,
      _engine_id);
}


inline bool operator==(const EngineContainerT &lhs, const EngineContainerT &rhs) {
  return
      (lhs.engines.size() == rhs.engines.size() && std::equal(lhs.engines.cbegin(), lhs.engines.cend(), rhs.engines.cbegin(), [](std::unique_ptr<hipdnn_sdk::data_objects::EngineT> const &a, std::unique_ptr<hipdnn_sdk::data_objects::EngineT> const &b) { return (a == b) || (a && b && *a == *b); }));
}

inline bool operator!=(const EngineContainerT &lhs, const EngineContainerT &rhs) {
    return !(lhs == rhs);
}


inline EngineContainerT::EngineContainerT(const EngineContainerT &o) {
  engines.reserve(o.engines.size());
  for (const auto &engines_ : o.engines) { engines.emplace_back((engines_) ? new hipdnn_sdk::data_objects::EngineT(*engines_) : nullptr); }
}

inline EngineContainerT &EngineContainerT::operator=(EngineContainerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(engines, o.engines);
  return *this;
}

inline EngineContainerT *EngineContainer::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EngineContainerT>(new EngineContainerT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EngineContainer::UnPackTo(EngineContainerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = engines(); if (_e) { _o->engines.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->engines[_i]) { _e->Get(_i)->UnPackTo(_o->engines[_i].get(), _resolver); } else { _o->engines[_i] = std::unique_ptr<hipdnn_sdk::data_objects::EngineT>(_e->Get(_i)->UnPack(_resolver)); }; } } else { _o->engines.resize(0); } }
}

inline ::flatbuffers::Offset<EngineContainer> EngineContainer::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineContainerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEngineContainer(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EngineContainer> CreateEngineContainer(::flatbuffers::FlatBufferBuilder &_fbb, const EngineContainerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EngineContainerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _engines = _o->engines.size() ? _fbb.CreateVector<::flatbuffers::Offset<hipdnn_sdk::data_objects::Engine>> (_o->engines.size(), [](size_t i, _VectorArgs *__va) { return CreateEngine(*__va->__fbb, __va->__o->engines[i].get(), __va->__rehasher); }, &_va ) : 0;
  return hipdnn_sdk::data_objects::CreateEngineContainer(
      _fbb,
      _engines);
}

inline const hipdnn_sdk::data_objects::EngineContainer *GetEngineContainer(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_sdk::data_objects::EngineContainer>(buf);
}

inline const hipdnn_sdk::data_objects::EngineContainer *GetSizePrefixedEngineContainer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_sdk::data_objects::EngineContainer>(buf);
}

inline EngineContainer *GetMutableEngineContainer(void *buf) {
  return ::flatbuffers::GetMutableRoot<EngineContainer>(buf);
}

inline hipdnn_sdk::data_objects::EngineContainer *GetMutableSizePrefixedEngineContainer(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_sdk::data_objects::EngineContainer>(buf);
}

inline bool VerifyEngineContainerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_sdk::data_objects::EngineContainer>(nullptr);
}

inline bool VerifySizePrefixedEngineContainerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_sdk::data_objects::EngineContainer>(nullptr);
}

inline void FinishEngineContainerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::EngineContainer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEngineContainerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::EngineContainer> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hipdnn_sdk::data_objects::EngineContainerT> UnPackEngineContainer(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::EngineContainerT>(GetEngineContainer(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_sdk::data_objects::EngineContainerT> UnPackSizePrefixedEngineContainer(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::EngineContainerT>(GetSizePrefixedEngineContainer(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_ENGINE_HIPDNN_SDK_DATA_OBJECTS_H_
