// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINEDETAILS_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_ENGINEDETAILS_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct EngineDetails;
struct EngineDetailsBuilder;
struct EngineDetailsT;

bool operator==(const EngineDetailsT &lhs, const EngineDetailsT &rhs);
bool operator!=(const EngineDetailsT &lhs, const EngineDetailsT &rhs);

struct EngineDetailsT : public ::flatbuffers::NativeTable {
  typedef EngineDetails TableType;
  int64_t engine_id = 0;
};

struct EngineDetails FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineDetailsT NativeTableType;
  typedef EngineDetailsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENGINE_ID = 4
  };
  int64_t engine_id() const {
    return GetField<int64_t>(VT_ENGINE_ID, 0);
  }
  bool mutate_engine_id(int64_t _engine_id = 0) {
    return SetField<int64_t>(VT_ENGINE_ID, _engine_id, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ENGINE_ID, 8) &&
           verifier.EndTable();
  }
  EngineDetailsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(EngineDetailsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<EngineDetails> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineDetailsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct EngineDetailsBuilder {
  typedef EngineDetails Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_engine_id(int64_t engine_id) {
    fbb_.AddElement<int64_t>(EngineDetails::VT_ENGINE_ID, engine_id, 0);
  }
  explicit EngineDetailsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineDetails> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineDetails>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineDetails> CreateEngineDetails(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t engine_id = 0) {
  EngineDetailsBuilder builder_(_fbb);
  builder_.add_engine_id(engine_id);
  return builder_.Finish();
}

::flatbuffers::Offset<EngineDetails> CreateEngineDetails(::flatbuffers::FlatBufferBuilder &_fbb, const EngineDetailsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const EngineDetailsT &lhs, const EngineDetailsT &rhs) {
  return
      (lhs.engine_id == rhs.engine_id);
}

inline bool operator!=(const EngineDetailsT &lhs, const EngineDetailsT &rhs) {
    return !(lhs == rhs);
}


inline EngineDetailsT *EngineDetails::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<EngineDetailsT>(new EngineDetailsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void EngineDetails::UnPackTo(EngineDetailsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = engine_id(); _o->engine_id = _e; }
}

inline ::flatbuffers::Offset<EngineDetails> EngineDetails::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const EngineDetailsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateEngineDetails(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<EngineDetails> CreateEngineDetails(::flatbuffers::FlatBufferBuilder &_fbb, const EngineDetailsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const EngineDetailsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _engine_id = _o->engine_id;
  return hipdnn_sdk::data_objects::CreateEngineDetails(
      _fbb,
      _engine_id);
}

inline const hipdnn_sdk::data_objects::EngineDetails *GetEngineDetails(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_sdk::data_objects::EngineDetails>(buf);
}

inline const hipdnn_sdk::data_objects::EngineDetails *GetSizePrefixedEngineDetails(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_sdk::data_objects::EngineDetails>(buf);
}

inline EngineDetails *GetMutableEngineDetails(void *buf) {
  return ::flatbuffers::GetMutableRoot<EngineDetails>(buf);
}

inline hipdnn_sdk::data_objects::EngineDetails *GetMutableSizePrefixedEngineDetails(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_sdk::data_objects::EngineDetails>(buf);
}

inline bool VerifyEngineDetailsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_sdk::data_objects::EngineDetails>(nullptr);
}

inline bool VerifySizePrefixedEngineDetailsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_sdk::data_objects::EngineDetails>(nullptr);
}

inline void FinishEngineDetailsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::EngineDetails> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEngineDetailsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::EngineDetails> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hipdnn_sdk::data_objects::EngineDetailsT> UnPackEngineDetails(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::EngineDetailsT>(GetEngineDetails(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_sdk::data_objects::EngineDetailsT> UnPackSizePrefixedEngineDetails(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::EngineDetailsT>(GetSizePrefixedEngineDetails(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_ENGINEDETAILS_HIPDNN_SDK_DATA_OBJECTS_H_
