// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace hipdnn_sdk {
namespace data_objects {

struct ExecutionPlan;
struct ExecutionPlanBuilder;
struct ExecutionPlanT;

bool operator==(const ExecutionPlanT &lhs, const ExecutionPlanT &rhs);
bool operator!=(const ExecutionPlanT &lhs, const ExecutionPlanT &rhs);

struct ExecutionPlanT : public ::flatbuffers::NativeTable {
  typedef ExecutionPlan TableType;
  int64_t engine_id = 0;
  uint64_t data_ptr = 0;
};

struct ExecutionPlan FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExecutionPlanT NativeTableType;
  typedef ExecutionPlanBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENGINE_ID = 4,
    VT_DATA_PTR = 6
  };
  int64_t engine_id() const {
    return GetField<int64_t>(VT_ENGINE_ID, 0);
  }
  bool mutate_engine_id(int64_t _engine_id = 0) {
    return SetField<int64_t>(VT_ENGINE_ID, _engine_id, 0);
  }
  uint64_t data_ptr() const {
    return GetField<uint64_t>(VT_DATA_PTR, 0);
  }
  bool mutate_data_ptr(uint64_t _data_ptr = 0) {
    return SetField<uint64_t>(VT_DATA_PTR, _data_ptr, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_ENGINE_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_DATA_PTR, 8) &&
           verifier.EndTable();
  }
  ExecutionPlanT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ExecutionPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<ExecutionPlan> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ExecutionPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ExecutionPlanBuilder {
  typedef ExecutionPlan Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_engine_id(int64_t engine_id) {
    fbb_.AddElement<int64_t>(ExecutionPlan::VT_ENGINE_ID, engine_id, 0);
  }
  void add_data_ptr(uint64_t data_ptr) {
    fbb_.AddElement<uint64_t>(ExecutionPlan::VT_DATA_PTR, data_ptr, 0);
  }
  explicit ExecutionPlanBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExecutionPlan> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExecutionPlan>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExecutionPlan> CreateExecutionPlan(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t engine_id = 0,
    uint64_t data_ptr = 0) {
  ExecutionPlanBuilder builder_(_fbb);
  builder_.add_data_ptr(data_ptr);
  builder_.add_engine_id(engine_id);
  return builder_.Finish();
}

::flatbuffers::Offset<ExecutionPlan> CreateExecutionPlan(::flatbuffers::FlatBufferBuilder &_fbb, const ExecutionPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const ExecutionPlanT &lhs, const ExecutionPlanT &rhs) {
  return
      (lhs.engine_id == rhs.engine_id) &&
      (lhs.data_ptr == rhs.data_ptr);
}

inline bool operator!=(const ExecutionPlanT &lhs, const ExecutionPlanT &rhs) {
    return !(lhs == rhs);
}


inline ExecutionPlanT *ExecutionPlan::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ExecutionPlanT>(new ExecutionPlanT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void ExecutionPlan::UnPackTo(ExecutionPlanT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = engine_id(); _o->engine_id = _e; }
  { auto _e = data_ptr(); _o->data_ptr = _e; }
}

inline ::flatbuffers::Offset<ExecutionPlan> ExecutionPlan::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ExecutionPlanT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateExecutionPlan(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<ExecutionPlan> CreateExecutionPlan(::flatbuffers::FlatBufferBuilder &_fbb, const ExecutionPlanT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ExecutionPlanT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _engine_id = _o->engine_id;
  auto _data_ptr = _o->data_ptr;
  return hipdnn_sdk::data_objects::CreateExecutionPlan(
      _fbb,
      _engine_id,
      _data_ptr);
}

inline const hipdnn_sdk::data_objects::ExecutionPlan *GetExecutionPlan(const void *buf) {
  return ::flatbuffers::GetRoot<hipdnn_sdk::data_objects::ExecutionPlan>(buf);
}

inline const hipdnn_sdk::data_objects::ExecutionPlan *GetSizePrefixedExecutionPlan(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hipdnn_sdk::data_objects::ExecutionPlan>(buf);
}

inline ExecutionPlan *GetMutableExecutionPlan(void *buf) {
  return ::flatbuffers::GetMutableRoot<ExecutionPlan>(buf);
}

inline hipdnn_sdk::data_objects::ExecutionPlan *GetMutableSizePrefixedExecutionPlan(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hipdnn_sdk::data_objects::ExecutionPlan>(buf);
}

inline bool VerifyExecutionPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<hipdnn_sdk::data_objects::ExecutionPlan>(nullptr);
}

inline bool VerifySizePrefixedExecutionPlanBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<hipdnn_sdk::data_objects::ExecutionPlan>(nullptr);
}

inline void FinishExecutionPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::ExecutionPlan> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedExecutionPlanBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hipdnn_sdk::data_objects::ExecutionPlan> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hipdnn_sdk::data_objects::ExecutionPlanT> UnPackExecutionPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::ExecutionPlanT>(GetExecutionPlan(buf)->UnPack(res));
}

inline std::unique_ptr<hipdnn_sdk::data_objects::ExecutionPlanT> UnPackSizePrefixedExecutionPlan(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hipdnn_sdk::data_objects::ExecutionPlanT>(GetSizePrefixedExecutionPlan(buf)->UnPack(res));
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_EXECUTIONPLAN_HIPDNN_SDK_DATA_OBJECTS_H_
