// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TENSORATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_TENSORATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

#include "data_types_generated.h"

namespace hipdnn_sdk {
namespace data_objects {

struct TensorAttributes;
struct TensorAttributesBuilder;
struct TensorAttributesT;

bool operator==(const TensorAttributesT &lhs, const TensorAttributesT &rhs);
bool operator!=(const TensorAttributesT &lhs, const TensorAttributesT &rhs);

struct TensorAttributesT : public ::flatbuffers::NativeTable {
  typedef TensorAttributes TableType;
  int64_t uid = 0;
  std::string name{};
  hipdnn_sdk::data_objects::DataType data_type = hipdnn_sdk::data_objects::DataType_UNSET;
  std::vector<int64_t> strides{};
  std::vector<int64_t> dims{};
  bool virtual_ = false;
};

struct TensorAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TensorAttributesT NativeTableType;
  typedef TensorAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UID = 4,
    VT_NAME = 6,
    VT_DATA_TYPE = 8,
    VT_STRIDES = 10,
    VT_DIMS = 12,
    VT_VIRTUAL_ = 14
  };
  int64_t uid() const {
    return GetField<int64_t>(VT_UID, 0);
  }
  bool mutate_uid(int64_t _uid = 0) {
    return SetField<int64_t>(VT_UID, _uid, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  ::flatbuffers::String *mutable_name() {
    return GetPointer<::flatbuffers::String *>(VT_NAME);
  }
  hipdnn_sdk::data_objects::DataType data_type() const {
    return static_cast<hipdnn_sdk::data_objects::DataType>(GetField<int8_t>(VT_DATA_TYPE, 0));
  }
  bool mutate_data_type(hipdnn_sdk::data_objects::DataType _data_type = static_cast<hipdnn_sdk::data_objects::DataType>(0)) {
    return SetField<int8_t>(VT_DATA_TYPE, static_cast<int8_t>(_data_type), 0);
  }
  const ::flatbuffers::Vector<int64_t> *strides() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_STRIDES);
  }
  ::flatbuffers::Vector<int64_t> *mutable_strides() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_STRIDES);
  }
  const ::flatbuffers::Vector<int64_t> *dims() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_DIMS);
  }
  ::flatbuffers::Vector<int64_t> *mutable_dims() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_DIMS);
  }
  bool virtual_() const {
    return GetField<uint8_t>(VT_VIRTUAL_, 0) != 0;
  }
  bool mutate_virtual_(bool _virtual_ = 0) {
    return SetField<uint8_t>(VT_VIRTUAL_, static_cast<uint8_t>(_virtual_), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_UID, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_STRIDES) &&
           verifier.VerifyVector(strides()) &&
           VerifyOffset(verifier, VT_DIMS) &&
           verifier.VerifyVector(dims()) &&
           VerifyField<uint8_t>(verifier, VT_VIRTUAL_, 1) &&
           verifier.EndTable();
  }
  TensorAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TensorAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TensorAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TensorAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TensorAttributesBuilder {
  typedef TensorAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uid(int64_t uid) {
    fbb_.AddElement<int64_t>(TensorAttributes::VT_UID, uid, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(TensorAttributes::VT_NAME, name);
  }
  void add_data_type(hipdnn_sdk::data_objects::DataType data_type) {
    fbb_.AddElement<int8_t>(TensorAttributes::VT_DATA_TYPE, static_cast<int8_t>(data_type), 0);
  }
  void add_strides(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> strides) {
    fbb_.AddOffset(TensorAttributes::VT_STRIDES, strides);
  }
  void add_dims(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> dims) {
    fbb_.AddOffset(TensorAttributes::VT_DIMS, dims);
  }
  void add_virtual_(bool virtual_) {
    fbb_.AddElement<uint8_t>(TensorAttributes::VT_VIRTUAL_, static_cast<uint8_t>(virtual_), 0);
  }
  explicit TensorAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TensorAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TensorAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TensorAttributes> CreateTensorAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    hipdnn_sdk::data_objects::DataType data_type = hipdnn_sdk::data_objects::DataType_UNSET,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> strides = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> dims = 0,
    bool virtual_ = false) {
  TensorAttributesBuilder builder_(_fbb);
  builder_.add_uid(uid);
  builder_.add_dims(dims);
  builder_.add_strides(strides);
  builder_.add_name(name);
  builder_.add_virtual_(virtual_);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TensorAttributes> CreateTensorAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t uid = 0,
    const char *name = nullptr,
    hipdnn_sdk::data_objects::DataType data_type = hipdnn_sdk::data_objects::DataType_UNSET,
    const std::vector<int64_t> *strides = nullptr,
    const std::vector<int64_t> *dims = nullptr,
    bool virtual_ = false) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto strides__ = strides ? _fbb.CreateVector<int64_t>(*strides) : 0;
  auto dims__ = dims ? _fbb.CreateVector<int64_t>(*dims) : 0;
  return hipdnn_sdk::data_objects::CreateTensorAttributes(
      _fbb,
      uid,
      name__,
      data_type,
      strides__,
      dims__,
      virtual_);
}

::flatbuffers::Offset<TensorAttributes> CreateTensorAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const TensorAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const TensorAttributesT &lhs, const TensorAttributesT &rhs) {
  return
      (lhs.uid == rhs.uid) &&
      (lhs.name == rhs.name) &&
      (lhs.data_type == rhs.data_type) &&
      (lhs.strides == rhs.strides) &&
      (lhs.dims == rhs.dims) &&
      (lhs.virtual_ == rhs.virtual_);
}

inline bool operator!=(const TensorAttributesT &lhs, const TensorAttributesT &rhs) {
    return !(lhs == rhs);
}


inline TensorAttributesT *TensorAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TensorAttributesT>(new TensorAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TensorAttributes::UnPackTo(TensorAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = uid(); _o->uid = _e; }
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = data_type(); _o->data_type = _e; }
  { auto _e = strides(); if (_e) { _o->strides.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->strides[_i] = _e->Get(_i); } } else { _o->strides.resize(0); } }
  { auto _e = dims(); if (_e) { _o->dims.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->dims[_i] = _e->Get(_i); } } else { _o->dims.resize(0); } }
  { auto _e = virtual_(); _o->virtual_ = _e; }
}

inline ::flatbuffers::Offset<TensorAttributes> TensorAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TensorAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTensorAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TensorAttributes> CreateTensorAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const TensorAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TensorAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _uid = _o->uid;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _data_type = _o->data_type;
  auto _strides = _o->strides.size() ? _fbb.CreateVector(_o->strides) : 0;
  auto _dims = _o->dims.size() ? _fbb.CreateVector(_o->dims) : 0;
  auto _virtual_ = _o->virtual_;
  return hipdnn_sdk::data_objects::CreateTensorAttributes(
      _fbb,
      _uid,
      _name,
      _data_type,
      _strides,
      _dims,
      _virtual_);
}

}  // namespace data_objects
}  // namespace hipdnn_sdk

#endif  // FLATBUFFERS_GENERATED_TENSORATTRIBUTES_HIPDNN_SDK_DATA_OBJECTS_H_
